"""Create endpoint_permission table

Revision ID: e926cd6a80c1
Revises: aa7793c20651
Create Date: 2025-05-13 10:18:58.523178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e926cd6a80c1'
down_revision = 'aa7793c20651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_name', sa.String(length=100), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoint_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoint_permissions_endpoint_name'), ['endpoint_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endpoint_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoint_permissions_endpoint_name'))

    op.drop_table('endpoint_permissions')
    # ### end Alembic commands ###
